<a href="https://colab.research.google.com/github/harttu/courses/blob/main/DeepLearningWithPytorch/Chapter5_model_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
t_c = [ 0.5, 14.0, 28.0, 11.0,  8.0,  3.0, -4.0,  6.0, 13.0, 21.0 ]
t_u = [35.7, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4 ]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)

In [ ]:
def model(t_u, w, b):
  return w * t_u + b

def loss_fn(t_p,t_c):
  return ((t_p - t_c ) ** 2).mean()


In [ ]:
w = torch.ones(())
b = torch.zeros(())

In [ ]:
t_p = model(t_u,w,b)

In [ ]:
t_p,t_c

(tensor([35.7000, 58.2000, 81.9000, 56.3000, 48.9000, 33.9000, 21.8000, 48.4000,
         60.4000, 68.4000]),
 tensor([ 0.5000, 14.0000, 28.0000, 11.0000,  8.0000,  3.0000, -4.0000,  6.0000,
         13.0000, 21.0000]))

In [ ]:
loss_fn(t_p,t_c)

tensor(1773.4521)

Naivi tapa laskea kulmakerrointa. Ei skaalaudu

In [ ]:
delta = 0.1

loss_rate_of_change_w = \
  (loss_fn(model(t_u, w + delta, b), t_c) -
   loss_fn(model(t_u, w - delta, b), t_c)) / ( 2.0 * delta )

In [ ]:
learning_rate = 1e-2

w  = w - learning_rate * loss_rate_of_change_w

In [ ]:
loss_rate_of_change_b = \
  ( loss_fn( model( t_u, w, b + delta ), t_c ) -
    loss_fn( model( t_u, w, b - delta ), t_c ) ) / (2.0 * delta) 

b = b - learning_rate * loss_rate_of_change_b

tensor(-4557.5000)

Eli nykyisessä w:n ja b:n ympäristössä, LOSSin arvo muuttuu seuraavissa suhteissa pieniin w:n ja b:n muutoksiin

In [ ]:
loss_rate_of_change_w,loss_rate_of_change_b

(tensor(4512.2261), tensor(-4557.5000))

In [ ]:
def dloss_fn(t_p,t_c):
  dsquared_diffs = 2 * ( t_p - t_c) / t_p.size(0) # t_p.size(0) -> 10
  return dsquared_diffs

In [ ]:
t_p.size(0)

10

In [ ]:

def dmodel_dw(t_u,w,b):
  return t_u


def dmodel_db(t_u,w,b):
  return 1


In [ ]:
def grad_fn(t_u,t_c,t_p,w,b):
  dloss_dtp = dloss_fn(t_p,t_c)
  dloss_dw = dloss_dtp * dmodel_dw(t_u,w,b)
  dloss_db = dloss_dtp * dmodel_db(t_u,w,b)
  return torch.stack( [ dloss_dw.sum(), dloss_db.sum() ] )

In [ ]:
def training_loop( n_epochs, learning_rate, params, t_u, t_c):
  for epoch in range(1, n_epochs + 1):
    w, b = params
    print("W:{}, b:{}".format(w,b))
    t_p = model(t_u,w,b)
    loss = loss_fn(t_p,t_c)
    grad = grad_fn(t_u,t_c,t_p,w,b)

    params = params - learning_rate * grad

    print('Epochs %d, Loss %f' % (epoch, float(loss)))

  return params

In [ ]:
training_loop(n_epochs = 100,
              learning_rate = 1e-2,
              params = torch.tensor([1.0,0.0]),
              t_u = t_u,
              t_c = t_c)

W:1.0, b:0.0
Epochs 1, Loss 1773.452148
W:-44.12224197387695, b:-0.8267999887466431
Epochs 2, Loss 5751988.500000
W:2548.907470703125, b:44.73957443237305
Epochs 3, Loss 18994931712.000000
W:-146462.140625, b:-2575.720947265625
Epochs 4, Loss 62727775059968.000000
W:8416610.0, b:148009.78125
Epochs 5, Loss 207148695047634944.000000
W:-483669024.0, b:-8505542.0
Epochs 6, Loss 684075954249301753856.000000
W:27794532352.0, b:488779616.0
Epochs 7, Loss 2259053707561858129461248.000000
W:-1597240901632.0, b:-28088215552.0
Epochs 8, Loss 7460168486342098124332335104.000000
W:91787074994176.0, b:1614117863424.0
Epochs 9, Loss 24636036786577379134549421719552.000000
W:-5274637525057536.0, b:-92756915519488.0
Epochs 10, Loss 81356651859010834730600006544261120.000000
W:3.031124034726134e+17, b:5330371168174080.0
Epochs 11, Loss inf
W:-1.7418660019808764e+19, b:-3.0631517776510976e+17
Epochs 12, Loss inf
W:1.0009811010722023e+21, b:1.7602709470205444e+19
Epochs 13, Loss inf
W:-5.7522406384574755

tensor([nan, nan])